name: myAction
on:
  push:
    branches: main
  pull_request:
    branches: main
    
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout Specific Branch
    - uses: actions/checkout@v4
      with:
         ref: main
     
      
    
     
        

  
    
     
    
      
    
    
    
